FROM jupyter/scipy-notebook:python-3.10

RUN pip install jupyterlab-code-formatter jupyterlab-lsp

COPY ./demo.ipynb /home/jovyan/demo.ipynb

# ADD ./demo.ipynb /home/jovyan/demo.ipynb
# ADD http://example.com/demo.ipynb /home/jovyan/demo.ipynb


